#include "base.h"
#include "gb.h"
#include "opcodes_info.h"

OpcodesInfo::InfoCB OpcodesInfo::cb[256] =
{
    // 0x00
    { 8,  [](GB &_gb, u16 _pc) { return "RLC B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RLC C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RLC D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RLC E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RLC H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RLC L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RLC (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RLC A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RRC B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RRC C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RRC D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RRC E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RRC H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RRC L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RRC (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RRC A"; } },

    // 0x10
    { 8,  [](GB &_gb, u16 _pc) { return "RL B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RL C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RL D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RL E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RL H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RL L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RL (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RL A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RR B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RR C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RR D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RR E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RR H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RR L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RR (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RR A"; } },

    // 0x20
    { 8,  [](GB &_gb, u16 _pc) { return "SLA B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SLA C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SLA D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SLA E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SLA H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SLA L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SLA (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SLA A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRA B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRA C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRA D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRA E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRA H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRA L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SRA (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRA A"; } },

    // 0x30
    { 8,  [](GB &_gb, u16 _pc) { return "SWAP B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SWAP C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SWAP D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SWAP E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SWAP H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SWAP L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SWAP (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SWAP A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRL B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRL C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRL D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRL E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRL H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRL L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SRL (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SRL A"; } },

    // 0x40
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 0, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 0, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 0, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 0, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 0, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 0, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 0, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 0, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 1, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 1, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 1, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 1, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 1, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 1, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 1, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 1, A"; } },

    // 0x50
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 2, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 2, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 2, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 2, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 2, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 2, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 2, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 2, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 3, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 3, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 3, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 3, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 3, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 3, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 3, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 3, A"; } },

    // 0x60
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 4, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 4, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 4, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 4, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 4, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 4, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 4, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 4, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 5, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 5, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 5, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 5, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 5, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 5, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 5, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 5, A"; } },

    // 0x70
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 6, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 6, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 6, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 6, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 6, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 6, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 6, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 6, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "BIT 7, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, A"; } },

    // 0x80
    { 8,  [](GB &_gb, u16 _pc) { return "RES 0, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 0, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 0, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 0, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 0, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 0, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 0, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 0, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 1, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 1, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 1, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 1, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 1, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 1, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 1, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 1, A"; } },

    // 0x90
    { 8,  [](GB &_gb, u16 _pc) { return "RES 2, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 2, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 2, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 2, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 2, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 2, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 2, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 2, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 3, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 3, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 3, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 3, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 3, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 3, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 3, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 3, A"; } },

    // 0xA0
    { 8,  [](GB &_gb, u16 _pc) { return "RES 4, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 4, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 4, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 4, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 4, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 4, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 4, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 4, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 5, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 5, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 5, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 5, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 5, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 5, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 5, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 5, A"; } },

    // 0xB0
    { 8,  [](GB &_gb, u16 _pc) { return "RES 6, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 6, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 6, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 6, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 6, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 6, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 6, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 6, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 7, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 7, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 7, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 7, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 7, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 7, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "RES 7, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RES 7, A"; } },

    // 0xC0
    { 8,  [](GB &_gb, u16 _pc) { return "SET 0, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 0, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 0, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 0, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 0, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 0, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 0, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 0, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 1, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 1, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 1, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 1, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 1, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 1, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 1, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 1, A"; } },

    // 0xD0
    { 8,  [](GB &_gb, u16 _pc) { return "SET 2, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 2, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 2, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 2, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 2, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 2, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 2, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 2, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 3, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 3, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 3, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 3, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 3, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 3, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 3, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 3, A"; } },

    // 0xE0
    { 8,  [](GB &_gb, u16 _pc) { return "SET 4, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 4, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 4, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 4, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 4, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 4, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 4, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 4, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 5, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 5, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 5, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 5, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 5, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 5, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 5, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 5, A"; } },

    // 0xF0
    { 8,  [](GB &_gb, u16 _pc) { return "SET 6, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 6, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 6, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 6, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 6, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 6, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 6, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 6, A"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 7, B"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 7, C"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 7, D"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 7, E"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 7, H"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 7, L"; } },
    { 16, [](GB &_gb, u16 _pc) { return "SET 7, (HL)"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "SET 7, A"; } },
};