#include "base.h"
#include "gb.h"
#include "opcodes_info.h"

OpcodesInfo::InfoCB OpcodesInfo::cb[256] =
{
    // 0x00
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x10
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "RL C"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x20
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x30
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x40
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x50
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x60
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x70
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 8,  [](GB &_gb, u16 _pc) { return "BIT 7, H"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x80
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0x90
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0xA0
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0xB0
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0xC0
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0xD0
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0xE0
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },

    // 0xF0
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } },
    { 0,  [](GB &_gb, u16 _pc) { return "NO IMPLEMENTED"; } }
};